name: studydz-testing

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files for debugging
        run: ls -la

      - name: Install dependencies
        run: npm ci
        working-directory: ./study

      - name: Build and fix
        run: npm run build:fix
        working-directory: ./study

      - name: Start app
        run: npm start
        working-directory: ./study
